version: '3.9'

services:
  vpndb:
    image: postgres:14.7-alpine
    container_name: vpndb
    network_mode: host
    restart: unless-stopped
    expose:
      - "5433"
    command: -p 5433
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5433
    volumes:
      - vpndata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5433"]
      interval: 5s
      timeout: 45s
      retries: 5

  vpnbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vpnbot
    network_mode: host
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      vpndb: 
        condition: service_healthy

  ipsec:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro

  wireguard:
    build:
      context: .
      dockerfile: ./Dockerfile.wireguard
    restart: unless-stopped
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - wireguard-data:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  vpndata:
  ikev2-vpn-data:
  wireguard-data: